server:
  port: 4033

spring:
  datasource:
    url: jdbc:h2:file:C:\\Apps\\2024\\snooker_app\\h2_mem_db        # JDBC URL for in-memory H2 database
    driverClassName: org.h2.Driver
    username: admin                   # Default username
    password: admin                      # Default password
  h2:
    console:
      enabled: true                 # Enable H2 console (optional)
                  # Path to access H2 console (optional)

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update